initial_robot_configuration:

  ###############################
  # Initial robot configuration #
  ###############################

  com: [0.0, 0.0, 0.2]
  amom: [0.0, 0.0, 0.0]
  lmom: [0.0, 0.0, 0.0]
  # weight distribution, normalized by gravity * robot_weight
  eef_ctrl:
    eef_frc_rf: [0.0, 0.0, 0.25]
    eef_frc_lf: [0.0, 0.0, 0.25]
    eef_frc_rh: [0.0, 0.0, 0.25]
    eef_frc_lh: [0.0, 0.0, 0.25]

  # position of end effectors
  # [1.0,                   # end effector status
                            # 1.0 : active
                            # 0.0 : non-active
  #  0.10, -0.20, -0.32,    # position (x, y, z)
  #  1.0, 0.0, 0.0, 0.0]    # orientation in quaternions (w, q_x, q_y, q_z)
  eef_pose:
    eef_rf: [1.0, 0.20, -0.142, 0.0, 1.0, 0.0, 0.0, 0.0]
    eef_lf: [1.0, 0.20, 0.142, 0.0, 1.0, 0.0, 0.0, 0.0]
    eef_rh: [1.0, -0.20, -0.142, 0.0, 1.0, 0.0, 0.0, 0.0]
    eef_lh: [1.0, -0.20, 0.142, 0.0, 1.0, 0.0, 0.0, 0.0]


terrain_description:

  #######################
  # Terrain description #
  #######################

  regions: [[[1.00, 1.00, 0.0], [-1.00, 1.00, 0.0], [-1.00, -1.00, 0.0], [1.00, -1.00,
        0.0]]]


contact_plan:

  ################
  # Contact plan #
  ################

  # contact specification
  #  [0.0,                  # start time of contact
  #   1.9,                  # end time of contact
  #   0.10, -0.20, -0.32,   # position (x, y, z)
  #   1.0, 0.0, 0.0, 0.0,   # orientation in quaternions (w, q_x, q_y, q_z)
  #   1.0,                  # selecting contact type
  #                         # 1.0 : flat contact, forces subject to friction cone constrains of flat surface
  #                         # 2.0 : full contact, forces free in any direction (e.g. hand grasp)
  #  -1.0]                  # select the number of terrains in which the contact should lie
                            # -1.0 : no contact planning

  effcnt_rf:
  - [0.0, 1.0, 0.20, -0.142, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, -1.0]
  - [1.7, 3.0, 0.20, -0.142, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, -1.0]

  effcnt_lf:
  - [0.0, 1.0, 0.20, 0.142, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, -1.0]
  - [1.7, 3.0, 0.20, 0.142, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, -1.0]
  effcnt_rh:
  - [0.0, 1.0, -0.20, -0.142, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, -1.0]
  - [1.7, 3.0, -0.20, -0.142, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, -1.0]
  effcnt_lh:
  - [0.0, 1.0, -0.20, 0.142, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, -1.0]
  - [1.7, 3.0, -0.20, 0.142, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, -1.0]
  effvia_rf: []
  effvia_lf: []
  effvia_rh: []
  effvia_lh: []

planner_variables:

  #########################
  # Kinematics parameters #
  #########################

  load_kinematics: true
  display_motion: true
  num_dofs: 12
  kd_iterations: 2 # Number of dynamic and kinematic optimization iterations
  num_subsamples: 3
  active_dofs: [0, 1, 2, 3, 4, 5, 6, 7,8,9,10,11,12]
  min_joint_limits: [-2.5, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5]
  max_joint_limits: [2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5]
  default_joint_positions: [0., 0.52, -1.04, 0., 0.52, -1.04, 0., 0.52, -1.04, 0., 0.52, -1.04]
  
  #########################
  # Kinematics momentum parameters #
  #########################

  swing_traj_via_z: .4
  w_lin_mom_tracking: 20.
  w_ang_mom_tracking: 1.
  w_endeff_contact: 30.
  w_endeff_tracking: 0.1
  p_endeff_tracking: 0.
  p_com_tracking: .1
  w_joint_regularization: .05
  reg_orientation: 5.
  num_joint_viapoints: 0
  # via point definition, Not implemented yet the binding properly
  #  [time,                      # activation time of the via point
  # Front_left_hip, Front_left_knee,
  # Front_right_hip, Front_right_knee,
  # Back_left_hip, Back_left_knee,
  # Back_right_hip, Back_right_knee ]        # desired joint position
  joint_viapoints:
    via0: [1., 0.1, -0.2 ,0.1, -0.2 ,-0.1, 0.2 ,-0.1, 0.2]

  #########################
  # Kinematics parameters #
  #########################

  # load_kinopt: False
  # display_motion: False
  # display_contacts_plan: False
  # load_to_track_momentum: False
  # kd_iterations: 1
  # num_subsamples: 3
  # num_viapoints: [1, 1, 1, 1]
  # effvia_rf:
  #   via0: [ 1.50,        -0.100,  0.000, -0.200,    1.0, 0.0, 0.0, 0.0]
  # effvia_lf:
  #   via0: [ 1.50,         0.100,  0.000, -0.200,    1.0, 0.0, 0.0, 0.0]
  # effvia_rh:
  #   via0: [ 1.50,        -0.100,  0.400, -0.200,    1.0, 0.0, 0.0, 0.0]
  # effvia_lh:
  #   via0: [ 1.50,         0.100,  0.400, -0.200,    1.0, 0.0, 0.0, 0.0]
  # eff_rotation_dofs: []
  # active_dofs: [0, 1, 2, 3, 4, 5, 6, 7,   8, 9, 10, 11, 12, 13]
  # min_joint_angles: [-1.75, -1.75, -1.75, -1.75,  0.50,  0.50,  0.50,  0.50]
  # max_joint_angles: [-0.50, -0.50, -0.50, -0.50,  1.75,  1.75,  1.75,  1.75]
  # default_joints_state: [-0.401568, -0.89385, -0.447988, -0.91187, 0.431389, 0.959211, 0.397285, 0.876047]
  # use_noncvx_eff_orientation_opt: False
  # ang_vel_in_body_coordinates: True
  # num_base_ori_viapoints: 0
  # base_ori_viapoints:
  #   via0: [ 5.20,    0.9689, 0.0, 0.0, -0.2474]

  #######################
  # Dynamics parameters #
  #######################

  heuristic: TrustRegion  # Types: TrustRegion, SoftConstraint, TimeOptimization #
  n_act_eefs: 4
  # time step discretization
  time_step: 0.01
  time_horizon: 2.99
  external_force: [0.00, 0.00, 0.00]
  com_displacement: [0.00, 0.0, 0.00]
  # Will only read via points if this number is great than 0
  num_com_viapoints: 0
  # via point definition
  # [2.50                 # activation time of the via point
  #  0.500, 0.45,  0.00]  # position (x, y, z)
  com_viapoints:
    via0: [1.25, 0.00, 0.00, 0.7]

  #####################
  # Timing parameters #
  #####################

  max_time_iterations: 50
  max_time_residual_tolerance: 1e-3
  min_time_residual_improvement: 1e-5

  ############################
  # Configuration parameters #
  ############################

  gravity: 9.81
  robot_mass: 2.178
  friction_coeff: 0.3
  floor_height: 0.0
  # minimum allowed distance from the robot base to the floor
  min_rel_height: 0.05
  friction_cone: LinearCone  # Types: LinearCone, SocCone #
  time_range: [0.02, 0.25]
  is_time_horizon_fixed: true
  torque_range: [0.0, 0.0]
  eff_offset_rf: [0.200, -0.142, 0.000]
  eff_offset_lf: [0.200, 0.142, 0.000]
  eff_offset_rh: [-0.200, -0.142, 0.000]
  eff_offset_lh: [-0.200, 0.142, 0.000]
  cop_range_rf: [0.00, 0.00, 0.00, 0.00]
  cop_range_lf: [0.00, 0.00, 0.00, 0.00]
  cop_range_rh: [0.00, 0.00, 0.00, 0.00]
  cop_range_lh: [0.00, 0.00, 0.00, 0.00]
  max_eef_lengths: [0.3, 0.3, 0.3, 0.3]
  has_torque_limits: true
  min_torque_limits: [-2., -2., -2., -2., -2., -2., -2., -2., -2., -2., -2., -2.]
  max_torque_limits: [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]

  ####################
  # Dynamics weights #
  ####################

  w_trq_arm: 0.000
  w_trq_leg: 0.000
  w_time_penalty: 0.000
  w_time: 1000.0
  w_com: [1000., 1000.0, 10000] #cost weight of final com position
  w_amom: [0.010, 1.0, 0.010]
  w_lmom: [0.1, 0.1, 0.1]
  w_amomd: [0.100, 0.142, 0.100]
  w_lmomd: [0.005, 0.1, 0.005]
  w_amom_final: [10.00, 10.0, 10.00] # cost weight of final linear momentum
  w_lmom_final: [10.00, 10.0, 100.00] # cost weight of final angular momentum
  w_com_via: [0.000, 0.0, 0.000]
  w_frc_arm: [0.0, 0.0, 0.0]
  w_frc_leg: [0.0, 0.0, 0.0]
  w_dfrc_arm: [0.000, 0.0, 0.010]
  w_dfrc_leg: [0.000, 0.0, 0.010]
  w_com_track: [1.00, 1.00, 1.000] #cost weight of tracking of com trajectory from kinematic planner
  w_lmom_track: [1.00, 1.00, 1.00] #cost weight of tracking of linear momentum trajectory from kinematic planner
  w_amom_track: [1.000, 1.00, 1.000] #cost weight of tracking of angular momentum trajectory from kinematic planner

  ######################
  # Kinematics weights #
  ######################

  max_trajectory_iters: 5
  max_convergence_iters: 50
  convergence_tolerance: 1e-2
  integration_step: 1e-2
  slacks_penalty: 1e-2
  lambda_regularization: 1e-4

  w_kin_com: [10.00, 0.0, 10.00]
  w_kin_lmom: [1.e-3, 0.0, 1.e-4]
  w_kin_amom: [4.e-3, 0.00568, 0.000]
  w_kin_lmomd: [1.e-4, 0.000142, 1.e-4]
  w_kin_amomd: [1.e-3, 0.00142, 0.000]
  w_kin_eff_pos: [50.00, 14.2, 50.00]
  w_kin_eff_pos_nonact: [0.100, 1.42, 0.100]
  w_kin_base_ori: [1.e+0, 1.42e-08, 1.e-8]
  w_kin_default_joints: [1e-8, 1e-8, 1e-8, 1e-8, 1e-8, 1e-8, 1e-8, 1e-8]
  w_kin_joint_vel: [1e-6, 1e-6, 1e-6, 1e-8, 1e-8, 1e-8, 1e-6, 1e-6, 1e-6, 1e-6, 1e-6,
    1e-6, 1e-6, 1e-6]
  w_kin_joint_acc: [1e-6, 1e-6, 1e-6, 1e-8, 1e-8, 1e-8, 1e-6, 1e-6, 1e-6, 1e-6, 1e-6,
    1e-6, 1e-6, 1e-6]
                          # base                                 # joints

  #######################
  # Storage information #
  #######################

  store_data: true

  ##################
  # Solver setting #
  ##################

  use_default_solver_setting: false


solverlqr_dynamics:

  ############################
  # Lqr algorithm parameters #
  ############################

  verbosity: 0
  decimal_digits: 4
  lqr_max_iters: 1
  linesearch_coeff: 1.1
  linesearch_num_coeffs: 10
  cost_change_tolerance: 1e-9
  divergence_limit_check: 1e6
  bpass_regularization_type: 2
  bpass_min_regularization: 1e-6
  bpass_max_regularization: 1e10
  control_gradient_tolerance: 1e-6
  bpass_initial_regularization: 0.1
  min_expected_cost_improvement: 0.2
  bpass_mult_regularization_incr: 1.2
  bpass_initial_mult_regularization_incr: 1.0

  ##########################
  # Lqr problem parameters #
  ##########################

  problem_name: DynamicMomentumOptimization
  time_step: 0.01
  time_horizon: 2.99
  state_dimension: 9
  control_dimension: 12
  initial_state: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

  has_control_limits: false

  #######################
  # Storage information #
  #######################

  store_data: false

  ###################
  # User parameters #
  ###################

  user_parameters:
    control_cost: [0.001, 0.00142, 0.001]
    com_tracking: [1.0, 1.42, 1.0]
    lmom_tracking: [0.1, 0.142, 0.1]
    amom_tracking: [0.1, 0.142, 0.1]
    com_final_tracking: [1.0, 0.0, 1.0]
    lmom_final_tracking: [0.1, 0., 0.1]
    amom_final_tracking: [0.1, 0., 0.1]


solver_variables:

  ###########################
  # Branch and Bound solver #
  ###########################

  BnB_verbose: false
  BnB_max_iterations: 1000
  BnB_integer_tolerance: 1e-4
  BnB_absolute_suboptimality_gap: 1e-3
  BnB_relative_suboptimality_gap: 1e-6

  ##########################
  # Convergence tolerances #
  ##########################

  feasibility_tolerance: 1e-7
  max_residual_tolerance: 1e-3
  absolute_suboptimality_gap: 1e-7
  relative_suboptimality_gap: 1e-6
  max_indeterminate_tolerance: 1e-9
  feasibility_tolerance_inaccurate: 1e-4
  absolute_suboptimality_gap_inaccurate: 5e-5
  relative_suboptimality_gap_inaccurate: 5e-5

  ############################
  # Equilibration parameters #
  ############################

  equil_iterations: 3
  scaling_factor: 1.0
  equil_upper_bound: 1.0e3
  equil_lower_bound: 1.0e-3

  ############################
  # Linear System parameters #
  ############################

  dyn_reg_thresh: 1e-13
  lin_sys_accuracy: 1e-14
  err_reduction_factor: 6.0
  num_iter_ref_lin_solve: 9
  static_regularization: 7e-8
  dynamic_regularization: 2e-7

  cg_step_rate: 2.0
  cg_full_precision: 1e-9
  cg_residual_bound: 1e-18
  cg_reduced_precision: 1e-1

  ########################
  # Algorithm parameters #
  ########################

  safeguard: 500.0
  min_step_length: 1e-6
  max_step_length: 0.999
  min_centering_step: 1e-4
  max_centering_step: 1.00
  step_length_scaling: 0.99

  over_relaxation: 1.5
  optinfo_interval: 100
  converged_interval: 20
  consensus_penalty: 1e-3

  ####################
  # Model parameters #
  ####################

  verbose: false
  warm_start: false

  max_iters: 100
  ipsolver_max_iters: 100
  ipsolver_warm_iters: 100
  conicsolver_max_iters: 300
  conicsolver_warm_iters: 300

  num_itrefs_trustregion: 2
  trust_region_threshold: 0.15
  soft_constraint_weight_full: 1.0e4
  soft_constraint_weight_reduced: 1.0e4
